name: run-tests
on:
    push:
        branches:
        - main
        - master
    pull_request:
        branches:
        - main
        - master

jobs:
    test:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                julia_versions: [1.9.0, 1.9.1, 1.9.2, 1.10.0, 1.10.1, 1.10.2, 1.10.3]
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up julia v1.10.3
          uses: julia-actions/setup-julia@v1
          with:
            version: ${{matrix.julia_versions}}
        - name: Install dependencies
          run: julia -e 'using Pkg; Pkg.instantiate()'
        - name: Run tests
          run: julia --project -e 'using Pkg; Pkg.test()'
